// Embeds/reads a real PDF file attachment carrying one section's exact
// saved data (see sectionStorage.js's SectionRecord shape), so a section
// PDF this app generates can be turned back into layers losslessly — see
// SectionPdfButton (DeliverablesTab.jsx, write side) and "Generate layers
// from PDF" (LayerBuilder.jsx, read side).
//
// The visual PDF itself is still built the normal way (html2canvas + jsPDF
// — see multiPagePdfExport.js/SectionPdfButton) — this only does one extra
// post-processing step: load those bytes into @cantoo/pdf-lib and attach a
// JSON file. Plain jsPDF has no real attachment API (only 5 short metadata
// strings, or hiding text in the page content — neither is a genuine
// binary attachment); @cantoo/pdf-lib is a maintained pdf-lib fork with a
// real, documented attach()/getAttachments() pair, which the base pdf-lib
// package doesn't ship.
//
// Deliberately scoped to the per-section PDF only — the A4/A3 report PDFs
// are multi-section narrative documents, not a natural "layers" round-trip.
// Older PDFs generated before this existed simply have no attachment;
// readSectionDataFromPdf returns null for those rather than guessing.
import { PDFDocument } from '@cantoo/pdf-lib'

export const SECTION_PDF_ATTACHMENT_NAME = 'mid2030-session-data.json'
const SCHEMA_VERSION = 1

/**
 * @param {Uint8Array|ArrayBuffer} pdfBytes - the already-rendered PDF (jsPDF's own output).
 * @param {{ section: string, record: object }} data - the section's exact saved record.
 * @returns {Promise<Uint8Array>} the same PDF, plus the embedded attachment.
 */
export async function embedSectionDataInPdf(pdfBytes, { section, record }) {
  const pdfDoc = await PDFDocument.load(pdfBytes)
  const payload = { schemaVersion: SCHEMA_VERSION, section, record }
  await pdfDoc.attach(new TextEncoder().encode(JSON.stringify(payload)), SECTION_PDF_ATTACHMENT_NAME, {
    mimeType: 'application/json',
    description: 'MID 2030 app — machine-readable layer data for re-import via "Generate layers from PDF".',
  })
  return pdfDoc.save()
}

/**
 * @param {Uint8Array|ArrayBuffer} fileBytes - an uploaded PDF file.
 * @returns {Promise<{ schemaVersion: number, section: string, record: object } | null>}
 *   null if this PDF has no embedded section data (not generated by this
 *   app, or predates this feature) — never guessed/reconstructed from the
 *   PDF's visual content.
 */
export async function readSectionDataFromPdf(fileBytes) {
  const pdfDoc = await PDFDocument.load(fileBytes)
  const attachment = pdfDoc.getAttachments().find((a) => a.name === SECTION_PDF_ATTACHMENT_NAME)
  if (!attachment) return null

  const payload = JSON.parse(new TextDecoder().decode(attachment.data))
  if (payload.schemaVersion !== SCHEMA_VERSION) {
    throw new Error(`Unsupported PDF data version (${payload.schemaVersion ?? 'unknown'}) — expected ${SCHEMA_VERSION}.`)
  }
  return payload
}
